// Validation of request bodies against the limits the sim publishes in
// shared/limits.json (regenerated by `npm run shared` at the repo root). Shape
// and range only; the text filter is filter.ts.

import limits from '../../shared/limits.json' with { type: 'json' };

export const LIMITS: {
  causes: string[];
  maxMile: number;
  maxDay: number;
  crewSize: number;
  nameMax: number;
  epitaphMax: number;
  scoreMax: Record<'ceo' | 'sysadmin' | 'intern', number>;
} = limits;

export interface MemorialBody {
  runId: string;
  mile: number;
  day: number;
  cause: string;
  names: string[];
  epitaph: string;
}

export type Validated<T> = { ok: true; value: T } | { ok: false; error: string };

const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

function isInt(n: unknown, min: number, max: number): n is number {
  return typeof n === 'number' && Number.isInteger(n) && n >= min && n <= max;
}

export function validateMemorial(body: unknown): Validated<MemorialBody> {
  if (typeof body !== 'object' || body === null) return { ok: false, error: 'bad-body' };
  const b = body as Record<string, unknown>;
  if (typeof b['runId'] !== 'string' || !UUID.test(b['runId'])) return { ok: false, error: 'bad-run-id' };
  if (!isInt(b['mile'], 0, LIMITS.maxMile)) return { ok: false, error: 'bad-mile' };
  if (!isInt(b['day'], 1, LIMITS.maxDay)) return { ok: false, error: 'bad-day' };
  if (typeof b['cause'] !== 'string' || !LIMITS.causes.includes(b['cause'])) return { ok: false, error: 'bad-cause' };
  const names = b['names'];
  if (
    !Array.isArray(names) ||
    names.length < 1 ||
    names.length > LIMITS.crewSize ||
    !names.every((n) => typeof n === 'string' && n.length >= 1 && n.length <= LIMITS.nameMax)
  ) {
    return { ok: false, error: 'bad-names' };
  }
  if (typeof b['epitaph'] !== 'string' || b['epitaph'].length > LIMITS.epitaphMax) return { ok: false, error: 'bad-epitaph' };
  return {
    ok: true,
    value: { runId: b['runId'], mile: b['mile'], day: b['day'], cause: b['cause'], names: names as string[], epitaph: b['epitaph'] },
  };
}
